# Generated by Django 5.0.7 on 2024-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='customer',
            new_name='customer',
        ),
    ]
