# Generated by Django 5.0.7 on 2024-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
