# Generated by Django 5.0.7 on 2024-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0002_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_run',
        ),
        migrations.AddField(
            model_name='job',
            name='total_run',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
