# Generated by Django 5.0.7 on 2024-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0002_job_job_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='last_billed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_billed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
