# Generated by Django 5.0.7 on 2024-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0002_rename_mechanic_job_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
