# Generated by Django 5.0.7 on 2024-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0003_mechanic_last_billed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='last_billed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
