# Generated by Django 5.0.7 on 2024-07-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0003_job_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', null=True),
        ),
    ]
