# Generated by Django 5.0.7 on 2024-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0003_remove_service_total_run_job_total_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField()),
                ('emp_contact', models.CharField(max_length=10, unique=True)),
                ('emp_aadhaar', models.CharField(unique=True)),
                ('emp_address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
