# Generated by Django 5.0.7 on 2024-07-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0004_alter_customer_dues_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='previous_billed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_billed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
