# Generated by Django 5.0.7 on 2024-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0004_alter_mechanic_last_billed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='item_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
