# Generated by Django 5.0.7 on 2024-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_aadhaar',
            field=models.BigIntegerField(unique=True),
        ),
    ]
