# Generated by Django 5.0.7 on 2024-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0005_jobitem_item_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='service_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
