# Generated by Django 5.0.7 on 2024-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0005_customer_previous_billed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
