# Generated by Django 5.0.7 on 2024-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0006_alter_employee_emp_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_aadhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
