# Generated by Django 5.0.7 on 2024-07-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0006_alter_service_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='previous_billed_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='previous_billed_date',
        ),
    ]
