# Generated by Django 5.0.7 on 2024-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0006_rename_cost_service_service_cost_service_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_run',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
