# Generated by Django 5.0.7 on 2024-07-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0007_remove_customer_previous_billed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='svc.vendor'),
        ),
    ]
