# Generated by Django 5.0.7 on 2024-08-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0007_alter_employee_emp_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('Employee Wage', 'Employee Wage'), ('Other', 'other')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
