# Generated by Django 5.0.7 on 2024-08-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0008_employee_emp_payments_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_payments',
            new_name='emp_last_payment',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payments', to='svc.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Employee Payment', 'Employee Payment'), ('Other', 'other')]),
        ),
    ]
