# Generated by Django 5.0.7 on 2024-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0009_rename_emp_payments_employee_emp_last_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='specify_other',
            field=models.CharField(blank=True, null=True),
        ),
    ]
