# Generated by Django 5.0.7 on 2024-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0010_expense_specify_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='specify_other',
            new_name='expense_title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Employee Payment', 'Employee Payment'), ('Other', 'Other')]),
        ),
    ]
