# Generated by Django 5.0.7 on 2024-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0011_rename_specify_other_expense_expense_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_advance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
