# Generated by Django 5.0.7 on 2024-08-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0012_employee_emp_advance_employee_emp_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
