# Generated by Django 5.0.7 on 2024-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0013_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
